### ISSUE TITLE
Update Terraform Docs version to v0.17.0

### ISSUE THREAD

**Issue by byangtri** [terraform-docs/gh-actions#120]
### What problem are you facing?

Latest version of Terraform-docs is v0.17.0, https://github.com/terraform-docs/terraform-docs/releases/tag/v0.17.0

### How could terraform-docs help solve your problem?

Update Terraform Docs version to v0.17.0

**Comment by rchildress87** [comment]
I have submitted a PR to upgrade terraform-docs to v0.17.0. It is currently awaiting approval:

https://github.com/terraform-docs/gh-actions/pull/125

**Comment by byangtri** [comment]
@dickc-sg  - I see the PR has been merged, but the release version is not being updated and I prefer not to pull from main branch as there can be new changes

**Comment by rchildress87** [comment]
Thank you, @byangtri, for catching this. I am not familiar with the release process for this project and so I have raised the issue in the terraform-docs Slack workspace.

**Comment by RolfMoleman** [comment]
@white-james

**Comment by khos2ow** [comment]
#125 added support for terraform-docs v0.17.0 and I'm going to cut a release soon. Going to mark this as closed now.
