### ISSUE TITLE
Tag 1.2.0 missing from docker

### ISSUE THREAD

**Issue by luk2038649** [terraform-docs/gh-actions#133]
```
Warning: Docker pull failed with exit code 1, back off 6.118 seconds before retry.
  /usr/bin/docker pull quay.io/terraform-docs/gh-actions:1.2.0
  Error response from daemon: manifest for quay.io/terraform-docs/gh-actions:1.2.0 not found: manifest unknown: manifest unknown
Error: Docker pull failed with exit code 1
```

I have a github action that uses this project, its only pinned to @main 
```
    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
```

Its failing because it cant find the latest version which was released this morning.

I can just pin back to a previous version, but I wanted to drop a note here as others may experience this same issue.

Thanks for all your work on this great project.

**Comment by dunefro** [comment]
This has started to fail for us also. We are not able to pull the `1.2.0` tag. Should we use the `edge` release ?

**Comment by khos2ow** [comment]
We've just cut the `v1.2.0` release. Can you try again?

**Comment by luk2038649** [comment]
Worked great, thanks!

**Comment by anasillo** [comment]
For everyone else having the same issue, point the action to `v1` instead of `main`
```
    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1
      with:
```
