### ISSUE TITLE
v1.2.1 release missed

### ISSUE THREAD

**Issue by nitintutlani** [terraform-docs/gh-actions#140]
We started seeing this since morning: 

```
Warning: Docker pull failed with exit code 1, back off 7.292 seconds before retry.
  /usr/bin/docker pull quay.io/terraform-docs/gh-actions:1.2.1
  Error response from daemon: manifest for quay.io/terraform-docs/gh-actions:1.2.1 not found: manifest unknown: manifest unknown
```

Probably releasing v1.2.1 got missed after the main branch was updated. Please review

**Comment by pascal-hofmann** [comment]
Thanks for reporting. I created the missing v1.2.1 release. Can you confirm it's working again?

**Comment by khos2ow** [comment]
Should be good now. @nitintutlani can you try again?
