### ISSUE TITLE
Uncommitted change(s) error with 1.3.0

### ISSUE THREAD

**Issue by saliceti** [terraform-docs/gh-actions#145]
### Describe the bug
The new 1.3.0 version fails with error "Error: Uncommitted change(s) has been found!". The same code works fine on 1.2.2.

See runs:
- 1.2.2: https://github.com/DFE-Digital/terraform-modules/actions/runs/10957873664/job/30426913931
- 1.3.0: https://github.com/DFE-Digital/terraform-modules/actions/runs/10957492107/job/30425823032

### How can we reproduce it?
Repository: https://github.com/DFE-Digital/terraform-modules/
Fork and update the action to v1.3.0. Raising a PR will run the action.
Like: https://github.com/DFE-Digital/terraform-modules/actions/runs/10958001381/job/30427315881

### Environment information
- terraform-docs action version: 1.3.0

**Comment by pascal-hofmann** [comment]
This sounds like the generated code between terraform-docs 1.2.2 and 1.3.0 has changed, and you need to update the generated files in your repo. Did you try that?

**Comment by saliceti** [comment]
That was it thanks @pascal-hofmann . Looks like a subtle change from `<br>` to `<br/>`!
