### ISSUE TITLE
Show a clear error message if delimiters are missing

### ISSUE THREAD

**Issue by khos2ow** [terraform-docs/gh-actions#15]
When `output-file` doesn't contain required delimiters (i.e. `<!--- BEGIN_TF_DOCS --->` and `<!--- END_TF_DOCS --->`) the action fails without any explanation of what has happened. There needs to be a check against this and output a concise error message for user to identify and fix the issue.

**Comment by mkatneni** [comment]
This is my github action but it does not update template definition like I wanted it to do neither do I have get the default template definition what am I missing any directions please 
```      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v0.6.0
        with:
          working-dir: ./modules/s3
          output-file: README.md
          output-method: replace
          git-push: "true"
          template: |
            # Test tf11 basic

            ## Verify

            Should use the template defined instead of the default
            Should inject the table under usage

            # Usage

            <!--- BEGIN_TF_DOCS --->
            <!--- END_TF_DOCS --->```

**Comment by khos2ow** [comment]
Closing this in favor of #61.
