### ISSUE TITLE
Provided template is not taken into account 

### ISSUE THREAD

**Issue by mkatneni** [terraform-docs/gh-actions#37]
### Describe the bug
I wanted a template definition that goes at the top of my README so others are aware this is autogenerated by CI. But I couldnt get it to work as mentioned in the examples

### How can we reproduce it?

        uses: terraform-docs/gh-actions@v0.6.0
        with:
          working-dir: ./modules/s3
          output-file: README.md
          output-method: replace
          git-push: "true"
          template: |
            # S3 Module Documentation
            ## Verify

            Manually changing anything in the README will be overwritten 
           
            # Usage

**Comment by khos2ow** [comment]
@mkatneni Sorry for the delay, was there any error?
