### ISSUE TITLE
Upgrade to terraform-docs 0.13.0

### ISSUE THREAD

**Issue by wagnst** [terraform-docs/gh-actions#38]
As per https://github.com/terraform-docs/terraform-docs/releases/tag/v0.13.0
There is new terraform-docs version. Please update the actions (and readme) as well.

Seems a new container image is needed and to be referenced here: https://github.com/terraform-docs/gh-actions/blob/main/Dockerfile#L15

**Comment by fatbasstard** [comment]
Thanks @bappr , your fork works like a charm.

Would be great if could be "officially" implemented here

**Comment by khos2ow** [comment]
Apology for the delay, this is now fixed and will be available shortly in `v0.7.0`.
