### ISSUE TITLE
Show an error message when delimiters are missing

### ISSUE THREAD

**Issue by abeMedia** [terraform-docs/gh-actions#61]
### What problem are you facing?

When the delimiters `<!-- BEGIN_TF_DOCS -->` and `<!-- END_TF_DOCS -->` are missing the action fails siltently without giving any reason as to why, which can make debugging a nightmare in a big monorepo.

### How could terraform-docs help solve your problem?

It would be great if we could get an error message like `Delimiters are missing in path/to/USAGE.md`

**Comment by khos2ow** [comment]
Sorry for the *very* long delay!

This behavior has been changed as part of terraform-docs `v0.13.0` specifically https://github.com/terraform-docs/terraform-docs/commit/4be22230e7bcc4d73e8e69cf57528414903188ba, in which if the surrounding comments not found in the target file, they, along side the generated content, will be _appended_ to the target file.

This will be available in the upcoming `v1.0.0` release of gh-actions, in which native terraform-docs' output to file has been incorporated into behavior of the action (https://github.com/terraform-docs/gh-actions/pull/46)

**Comment by abeMedia** [comment]
Awesome, thanks!
