### ISSUE TITLE
Quay.io is down | Unable to pull Docker image

### ISSUE THREAD

**Issue by aditya-kar** [terraform-docs/gh-actions#66]
### Describe the bug

Unable to pull the Terraform Docs Docker image from Quay.io

### How can we reproduce it?

Try running the following command or just open quay.io in any web browser.

docker build --pull --tag quay.io/terraform-docs/gh-actions:edge .

### Environment information

This issue is not specific to any particular environment. Please consider moving to Docker Hub from Quay.io. Red HaT Quay appears to have been down for a while.

**Comment by khos2ow** [comment]
This seems to be a one off outage on Quay.io and we haven't noticed any more outages or downtime on their side. I'm gonna close this one for now. If you still had some issue with this please reopen.
