### ISSUE TITLE
Action not generating documentation as expected

### ISSUE THREAD

**Issue by tjrmentor** [terraform-docs/gh-actions#73]
### Describe the bug
I provide a simple example in which the action does not generate documentation that is generated by running the command directly in the command line.

### How can we reproduce it?
The workflow run in question is here: https://github.com/tjrmentor/terraform-docs-bug-report/runs/4731683196?check_suite_focus=true

To create this example, I did the following:
1. Created a brand new repository, and added `.github/workflows/test.yaml.` This is a workflow file that runs on pull requests to the `main` branch, which first validates the terraform and then uses the terraform-docs github action, in the form specified in the `README`  [here](https://github.com/terraform-docs/gh-actions#usage). I substitute `README.md` for `USAGE.md` and create the `README.md` file, with the injection tokens (`<!-- BEGIN_TF_DOCS -->` and `<!-- END_TF_DOCS -->`).
2. Created a new branch, added `main.tf` with a single test output, and created a pull request.
3. Observed that the run was successful, but that no documentation was generated.

On the other hand, when I run the command given in the output, `terraform-docs markdown table --indent 2  .`, it does generate documentation (the `"hello_world"` string output).

Expected behavior would be for the documentation to generate in the workflow run, and for a commit to be pushed.

### Environment information
Using terraform-docs/gh-actions@v0.11.0

**Comment by khos2ow** [comment]
That seemed a bit odd to happen and I did a little bit of digging and what's more strange is that it appears `quay.io/terraform-docs/gh-actions:0.11.0` does not have the correct content! Which I'm a bit baffled of why it's like this or how it happened. I'm gonna investigate and update my findings.

But in the meantime, for the purpose of your testing and validate your workflow, you can give this a try at: https://github.com/tjrmentor/terraform-docs-bug-report/blob/main/.github/workflows/test.yml#L36

```diff
-      uses: terraform-docs/gh-actions@v0.11.0
+      uses: terraform-docs/gh-actions@main
```

**Comment by tjrmentor** [comment]
As you said, `@main` works perfectly. I'm going to hold off on using this in my workflows until I can fix the version number, so I await your update.

**Comment by amenocal** [comment]
@tjrmentor @khos2ow 
Oh boy I spent hours trying to figure out why lines [113-119](https://github.com/terraform-docs/gh-actions/blob/main/src/docker-entrypoint.sh#L113-L119) were not being run! 

Updating to `@main` worked. I would recommend changing the docs in the [github actions page](https://github.com/marketplace/actions/terraform-docs-gh-actions)

**Comment by khos2ow** [comment]
Sorry for the __very__ long delay. [`v1.0.0`](https://github.com/terraform-docs/gh-actions/releases/tag/v1.0.0) has been released which addresses these issues.

Note that this is a breaking change release and some manual updates on your ends might be needed.

**Comment by khos2ow** [comment]
I'm gonna close this issue for housekeeping, please feel free to reopen or file new ones if needed.
