### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by robert-spring** [terraform-docs/gh-actions#92]
https://github.com/terraform-docs/gh-actions/blob/ac2a6b5864d9ea0a8f355156b162343b1f4d34b0/src/docker-entrypoint.sh#L180

needs to change to
```
echo "num_changed=${num_changed}" >> $GITHUB_ENV
```

**Comment by ViacheslavKudinov** [comment]
It still can be output, but
`echo "num_changed=${num_changed}" >> $GITHUB_OUTPUT`

**Comment by cocallaw** [comment]
Related issue https://github.com/terraform-docs/gh-actions/issues/95
